/**
 * SEO-CATEGORIES — grouping for the "explore" section on the homepage.
 * Purely presentational: maps each SeoPage `topic` to a category label,
 * used only to group the explore cards into rows on [lang]/index.astro.
 * Does not touch SEO_PAGES content or routing.
 */

export interface SeoCategory {
  id: string;
  label: { pl: string; en: string };
  topics: string[];
}

export const SEO_CATEGORIES: SeoCategory[] = [
  {
    id: "meet-people",
    label: { pl: "Poznawaj nowych ludzi", en: "Meet new people" },
    topics: [
      "random-chat",
      "anonymous-chat",
      "talk-to-strangers",
      "meet-new-people",
      "international-chat",
      "language-exchange",
      "meet-people-similar-interests",
    ],
  },
  {
    id: "dating-flirt",
    label: { pl: "Randki i flirt", en: "Dating and flirting" },
    topics: [
      "online-dating-chat",
      "flirt-chat-online",
      "random-dating-chat",
      "chat-to-find-love",
      "anonymous-dating-chat",
      "international-dating-chat",
      "chat-for-singles",
      "dating-chat-no-registration",
      "casual-chat-flirt",
      "dating-chat-app-alternative",
      "meet-someone-new-tonight",
      "safe-flirt-chat",
      "dating-chat-no-swiping",
      "dating-chat-casual-fun",
      "flirty-conversation-starters",
      "video-free-dating-chat",
      "chat-with-foreigners-dating",
      "weekend-flirt-chat",
      "chat-for-summer-flirt",
      "chat-for-holiday-flirt",
    ],
  },
  {
    id: "life-situations",
    label: { pl: "Dla Twojej sytuacji", en: "For your situation" },
    topics: [
      "chat-for-shy-singles",
      "text-based-dating",
      "chat-for-loneliness",
      "chat-for-shift-workers",
      "chat-while-traveling-solo",
      "chat-for-military-deployed",
      "chat-for-remote-workers",
      "chat-for-parents",
      "chat-for-quick-connection",
      "chat-for-slow-dating",
      "chat-for-genuine-connection",
      "chat-for-fresh-start-dating",
      "dating-chat-busy-professionals",
      "dating-chat-night-owls",
      "dating-chat-homebodies",
      "dating-chat-college-students",
      "dating-chat-relocating-singles",
      "dating-chat-single-parents",
      "dating-chat-starting-over",
      "dating-chat-comeback-dating",
      "long-distance-chat",
      "dating-chat-solo-travelers",
      "dating-chat-rainy-day",
      "dating-chat-post-work-unwind",
      "dating-chat-morning-person",
      "dating-chat-listener",
      "chat-to-boost-confidence-dating",
      "chat-to-improve-social-skills",
      "chat-first-date-practice",
      "dating-chat-social-skills",
    ],
  },
  {
    id: "interests",
    label: { pl: "Według zainteresowań", en: "By interest" },
    topics: [
      "chat-for-hobbyists",
      "chat-for-music-lovers",
      "chat-for-movie-fans",
      "chat-for-food-lovers",
      "chat-for-anime-fans",
      "dating-chat-anime-fans",
      "dating-chat-coffee-lovers",
      "dating-chat-foodies",
      "dating-chat-pet-lovers",
      "dating-chat-outdoorsy",
      "dating-chat-culture-lovers",
      "dating-chat-plant-lovers",
      "dating-chat-sports-fans",
      "dating-chat-writers",
      "dating-chat-science-fans",
      "dating-chat-fashion-lovers",
      "dating-chat-board-games",
      "dating-chat-astrology",
      "dating-chat-diy-crafts",
      "dating-chat-history-buffs",
      "dating-chat-podcast-fans",
      "dating-chat-vegan-vegetarian",
      "dating-chat-creative-people",
      "dating-chat-tech-people",
      "dating-chat-music-taste-match",
      "dating-chat-humor-match",
      "chat-for-witty-banter",
    ],
  },
  {
    id: "languages-countries",
    label: { pl: "Języki i kraje", en: "Languages and countries" },
    topics: [
      "practice-french-chat",
      "practice-italian-chat",
      "practice-portuguese-chat",
      "chat-with-korean-speakers",
      "chat-with-brazilian-speakers",
      "dating-chat-language-barrier",
      "dating-chat-bilingual",
      "dating-chat-language-learners-romance",
      "dating-chat-teach-your-language",
      "chat-for-second-language-flirting",
      "dating-chat-cross-cultural-romance",
      "chat-for-cultural-exchange-dating",
    ],
  },
  {
    id: "deeper-honest",
    label: { pl: "Na poważniej", en: "Something more real" },
    topics: [
      "chat-for-mature-singles",
      "dating-chat-long-term",
      "chat-for-honest-dating",
      "dating-chat-no-games",
      "chat-for-thoughtful-conversation",
      "dating-chat-deep-questions",
      "dating-chat-shared-values",
      "dating-chat-kind-people",
      "dating-chat-good-listener",
      "dating-chat-open-minded",
      "dating-chat-curious-people",
      "dating-chat-authentic-self",
      "dating-chat-body-positive-conversation",
      "dating-chat-before-meeting-irl",
      "dating-chat-friendship-first",
      "dating-chat-anonymous-crush",
      "chat-for-adventurous-singles",
      "dating-chat-icebreaker-questions",
      "dating-chat-first-message-help",
    ],
  },
];

/** Returns the category id a given topic belongs to, or "other" if unmatched. */
export function getCategoryForTopic(topic: string): string {
  const found = SEO_CATEGORIES.find((c) => c.topics.includes(topic));
  return found?.id ?? "other";
}
